use crate::utils;
use std::time::Instant;

// Stub generated by Elf
pub fn solve() {
    // elf splits the printed output at the first <space> and takes writes the first half as the solution
    let lines = utils::file_to_lines("{{year}}", "{{day}}");
    let mut time = Instant::now();
    let p1 = part_one(&lines);
    println!("{:?} in {:?} for Part 1", p1, time.elapsed());
    time = Instant::now();
    let p2 = part_two(&lines);
    println!("{:?} in {:?} for Part 2", p2, time.elapsed());
}

fn part_one(lines: &[String]) -> usize {
    0
}
fn part_two(lines: &[String]) -> usize {
    0
}
