use crate::utils;
use std::time::Instant;

// Stub generated by templar
pub fn solve() -> (String, String) {
    let lines = utils::file_to_lines("{{year}}", "{{day}}");
    let mut time = Instant::now();
    let p1 = String::from(part_one(&lines));
    println!("Part 1: {:?} in {:?}", p1, time.elapsed());
    time = Instant::now();
    let p2 = String::from(part_two(&lines));
    println!("Part 2: {:?} in {:?}", p2, time.elapsed());
    (p1, p2)
}

fn part_one(lines: &[String]) -> usize {
    0
}
fn part_two(lines: &[String]) -> usize {
    0
}
